<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="stl" nsURI="http://www.example.org/stl" nsPrefix="stl">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProductionLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="areas" upperBound="-1"
        eType="#//Area" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemtype" upperBound="-1"
        eType="#//ItemType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemType" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" upperBound="-1"
        eType="#//Connector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedparameter" upperBound="-1"
        eType="#//NamedParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" upperBound="-1" eType="#//Slot"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//NamedElement #//Costs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1" upperBound="-1"
        eType="#//Slot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SameItemTypesConnectedSlots SameAreaConnector"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SameItemTypesConnectedSlots" value="self.sourceComponent.itemtype = self.targetComponent.itemtype"/>
      <details key="SameAreaConnector" value="self.Area = self.sourceComponent.Area"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetComponent" lowerBound="1"
        eType="#//Slot" eOpposite="#//Slot/incomingConnetor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceComponent" lowerBound="1"
        eType="#//Slot" eOpposite="#//Slot/outgoingConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//NamedElement #//Costs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliability" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processingTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedparameter" eType="#//NamedParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conveyor" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OneInputSlotConveyor OneOutputSlotConveyor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="OneInputSlotConveyor" value="self.slot ->selectByType(InputSlot)-> size() = 1"/>
      <details key="OneOutputSlotConveyor" value="self.slot ->selectByType(OutputSlot)-> size() = 1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnTable" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AtLeastOneInputSlotTurnTable AtLeastOneOutputSlotTurnTable"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="AtLeastOneInputSlotTurnTable" value="self.slot ->selectByType(InputSlot)-> size() >= 1"/>
      <details key="AtLeastOneOutputSlotTurnTable" value="self.slot ->selectByType(OutputSlot)-> size() >= 1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AtLeastOneInputSlotMachine AtLeastOneOutputSlotMachine"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="AtLeastOneInputSlotMachine" value="self.slot ->selectByType(InputSlot)-> size() >= 1"/>
      <details key="AtLeastOneOutputSlotMachine" value="self.slot ->selectByType(OutputSlot)-> size() >= 1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OneInputSlotBuffer OneOutputSlotBuffer"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="OneInputSlotBuffer" value="self.slot ->selectByType(InputSlot)-> size() = 1"/>
      <details key="OneOutputSlotBuffer" value="self.slot ->selectByType(OutputSlot)-> size() = 1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemGenerator" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoInputSlotItemGenerator OneOutputSlotItemGenerator"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NoInputSlotItemGenerator" value="self.slot ->selectByType(InputSlot)-> size() = 0"/>
      <details key="OneOutputSlotItemGenerator" value="self.slot ->selectByType(OutputSlot)-> size() = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemtypes" lowerBound="1"
        eType="#//ItemType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WasteStore" eSuperTypes="#//Store">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OneInputSlotWasteStore NoOutputSlotWasteStore"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="OneInputSlotWasteStore" value="self.slot ->selectByType(InputSlot)-> size() = 1"/>
      <details key="NoOutputSlotWasteStore" value="self.slot ->selectByType(OutputSlot)-> size() = 0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductStore" eSuperTypes="#//Store">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OneInputSlotProductStore NoOutputSlotProductStore"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="OneInputSlotProductStore" value="self.slot ->selectByType(InputSlot)-> size() = 1"/>
      <details key="NoOutputSlotProductStore" value="self.slot ->selectByType(OutputSlot)-> size() = 0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Costs" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedParameter" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Slot" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemtype" lowerBound="1"
        eType="#//ItemType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnetor" upperBound="-1"
        eType="#//Connector" eOpposite="#//Connector/targetComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnector" upperBound="-1"
        eType="#//Connector" eOpposite="#//Connector/sourceComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputSlot" eSuperTypes="#//Slot"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputSlot" eSuperTypes="#//Slot"/>
</ecore:EPackage>
